name: global_gradient
description: A Flutter package for creating visual effects with globally positioned gradients.
version: 0.0.1
repository: https://github.com/blaugold/global_gradient/
issue_tracker: https://github.com/blaugold/global_gradient/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
